# Site settings
title: Templates
email: barry@br-web.io
description:
   Repository of website templates and components
baseurl: ""
url: ""

# Build settings
markdown: kramdown
port: 4000
livereload: true
permalink: pretty
include: ["_pages"]